# Generated by Django 5.2.1 on 2025-05-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
